# Site settings
title: Design Portfolio
description: "Sigi van Lindt's Design Portfolio"
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://sigi-technical.art" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Sigi van Lindt
user_description: 
user_title: Let's Shape Interactive Futures Together
email: svlindt@gmail.com
#twitter_username: lorem_ipsum
github_username:  Sogii
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
