# Site settings
title: Design Portfolio
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Sigi van Lindt
user_description: 
user_title: Industrial Design Master's Student | Making more personal user experiences
email: svlindt@gmail.com
#twitter_username: lorem_ipsum
github_username:  Sogii
#gplus_username:  lorem_ipsum

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
